name: filepicker_windows
description: A plugin that uses FFI to offer file selection in Windows using the modern common item dialog box.
version: 2.0.0-nullsafety.0
author:
homepage:

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  win32: ^1.7.4
  # ffi: ^0.2.0-nullsafety.1
  # win32: ^2.0.0-nullsafety.0

dev_dependencies:
  lint: ^1.5.1